### ISSUE TITLE
想请教一个问题

### ISSUE THREAD

**Issue by buzai** [jikeytang/sublime-text#4]
sublime代码提示的时候会很快地消失，选择有点费劲，有咩有方法设置让代码提示消失的时间长一点，不至于没看清楚之前就咩有了

**Comment by jikeytang** [comment]
我在win10测试sublimetext2,3，安装有sublimeCodeIntel插件，都没有发现你这个情况。代码提示一直存在，没有提前消失的情况。

**Comment by buzai** [comment]
谢谢您，我重新安装了一次系统他自己好了
